controllers:
    resource: '../src/Controller/'
    type: attribute
fallback:
    path: /{catchall}
    defaults: { _controller: App\Controller\DefaultController::index }
    requirements:
        catchall: ".*"